POST http://localhost:3333/api/subscriptions
Content-Type: application/json

{
  "name": "vito indicado 02",
  "email": "indicado02@icloud.com"
}

### 
GET http://localhost:3333/api/invites/730ff8f2-68e2-4f90-8d27-2271f9f6c977
### 
GET http://localhost:3333/api/subscribers/730ff8f2-68e2-4f90-8d27-2271f9f6c977/ranking/clicks

### 
GET http://localhost:3333/api/subscribers/730ff8f2-68e2-4f90-8d27-2271f9f6c977/ranking/position