
name: nlw-connect-nodejs:0.0.1

services:
  pg:
    container_name: nlw-connect-node-pg
    image: bitnami/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=albqvxc
      - POSTGRES_PASSWORD=albq123
      - POSTGRES_DB=nlw-connect-nodejs
    volumes:
      - pg-volume:/var/lib/postgresql/data
  
  redis:
    container_name: nlw-connect-node-redis
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  pg-volume: